name: Auto Build & Push on Upstream Changes

on:
  schedule:
    - cron: '0 2 * * *'  # Täglich um 2 Uhr UTC
  workflow_dispatch:      # Manuell auslösbar

jobs:
  auto-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout own repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add and fetch upstream repo
        run: |
          git remote add upstream https://github.com/crocofied/CoreControl.git
          git fetch upstream main

      - name: Check for upstream changes
        id: check_changes
        run: |
          if git diff --quiet upstream/main origin/main; then
            echo "No changes found."
            echo "update_required=false" >> $GITHUB_ENV
          else
            echo "Changes found. Building image..."
            echo "update_required=true" >> $GITHUB_ENV
          fi

      - name: Show changed files (if any)
        if: env.update_required == 'true'
        run: |
          echo "📜 Änderungen seit letztem Sync:"
          git diff --name-status upstream/main origin/main

      - name: Set up Docker Buildx
        if: env.update_required == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: env.update_required == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version tag from file (optional)
        if: env.update_required == 'true'
        id: extract_version
        run: |
          VERSION=$(grep -oE '"version":\s*"[^"]+"' package.json | cut -d '"' -f4 || echo "latest")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Verwende Versionstag: $VERSION"

      - name: Build and Push Docker Image with version tag
        if: env.update_required == 'true'
        run: |
          docker build -t fgrfn/corecontrol:latest -t fgrfn/corecontrol:$VERSION .
          docker push fgrfn/corecontrol:latest
          docker push fgrfn/corecontrol:$VERSION
